### PR TITLE
Document plugins

### PR DESCRIPTION
**Pull request by lukemarsden**
Documentation improvements to reflect the work done on plugins in general and volume plugins in particular.
- New "Docker Plugins" section in the user guide, explaining what they are and where you can get one.
- New "Plugin API" reference section for would-be authors of plugins, explaining how to build one and documenting the handshake and volumes API.
- Update `docker run` and `docker create` CLI docs to reflect the UX changes for `--volume-driver`.
- Update Remote API docs to reflect the backward compatible design for specifying volume drivers via the API.

### CODE REVIEW

**Comment by lukemarsden** [comment]
ping @calavera @icecrime

**Comment by calavera** [comment]
oh man, thank you so much for doing this. I'm reading it now.

**Comment by calavera** [comment]
This looks great! do you mind to squash the commits into a single one? I'll have less trouble porting this to mainstream that way

**Comment by lukemarsden** [comment]
you're welcome :) I'll squash the commits now.

**Comment by lukemarsden** [comment]
@calavera here you go: https://github.com/lukemarsden/docker/commit/2089241bc68266d4b9632109621533cb91494903

You should be able to just cherry-pick that commit or otherwise do as you wish with it. Not sure why a bunch of your branch's previous history showed up in this PR (I could swear it wasn't doing that when I submitted it).

**Comment by calavera** [comment]
:sparkles: thanks, cherry-picking and pushing to the main PR!

**Comment by calavera** [comment]
It lives in https://github.com/docker/docker/pull/13161 now :heart:

**Comment by lukemarsden** [comment]
Yay, thanks @calavera ! :heart:

**Pull request closed without merging**
