### PR TITLE
Disallow specifying the driver with -v

### PR DESCRIPTION
**Pull request by icecrime**
Signed-off-by: Arnaud Porterie arnaud.porterie@docker.com

### CODE REVIEW

**Comment by lukemarsden** [comment]
This might break the backwardly compatible API that we're depending on to get this working with swarm.

I've publicly documented only the `--volume-driver` option for `docker run` in #12: is this good enough?

**Comment by icecrime** [comment]
It's true, but I think it's going to be easier to just update Swarm to support `--volume-driver` through the API.

**Comment by calavera** [comment]
cool, thanks for the comment @icecrime. Let's go with only the `volume-driver` option for now. That poor `-v` is starting be clumsy and crowded.

**Comment by lukemarsden** [comment]
> It's true, but I think it's going to be easier to just update Swarm to support --volume-driver through the API.

@icecrime will you handle getting this swarm team on this? ;) cc @vieux @aluzzardi

**Pull request merged**
