### PR TITLE
Proposal : Move plugins as a Docker pkg

### PR DESCRIPTION
**Pull request by mavenugo**
Thanks to the current design, the Plugins system is very general & it
can infact be a pkg that can be reused by other projects if need be.

Signed-off-by: Madhu Venugopal madhu@docker.com

### CODE REVIEW

**Comment by progrium** [comment]
Haha, yes I suppose? It's still actually pretty Docker specific. I guess I don't have too strong an opinion, but I think I'd generally put this off until:
1. it's done :)
2. there is a clear example of another project that can use it

**Comment by mavenugo** [comment]
@progrium sure. Though libnetwork is an (experimental) user of this plugins mechanism https://github.com/mavenugo/libnetwork/commit/b3dcb1fc398e6102fe06774abe9748ca6525e15a, I certainly see an immediate need for an completely independent runtime that can use libnetwork independently of docker. (still having plugins deployed as docker containers - `inception reversed` ;) )

**Comment by progrium** [comment]
Ah yes. Looking at your code it probably means some changes might have to be made and certainly some better docs for it to be a better general package. If you guys can keep trying it out as it evolves, maybe we can work together later once it's done for it's primary use cases and then we can see what needs to be done to make it more properly general and usable for your use case?

**Comment by mavenugo** [comment]
@progrium just to make it clear, network-driver is a primary usecase for plugins. The secondary use-case that i bring up in this PR is to make plugins as a pkg and I agree that we can continue to explore as it evolves.

**Comment by progrium** [comment]
Yep yep. Can we close this for now since it's not a functional issue? And then when we move it under pkg I can make sure it's got some basic docs and such.

**Comment by mavenugo** [comment]
@progrium @calavera Can you please give an estimate on when we can see this available in Docker master ?
It would be good atleast if we have the APIs checked in so that we can start the integration work for `libnetwork`. there are many pending activities because of this and 1.7 is at risk for libnetwork.

**Comment by progrium** [comment]
Hopefully this week! I'm back on it later today.

**Comment by mavenugo** [comment]
@progrium thanks. any considerations to pushing just the APIs to the docker sooner so that we can start the integration work ?

**Comment by progrium** [comment]
I think we'd all like them to be at least a little more mature (read: works) and tested first, but yes we can try.

**Comment by calavera** [comment]
I opened a PR in docker/docker this morning for volume plugins: https://github.com/docker/docker/pull/13161

**Comment by mavenugo** [comment]
@calavera :+1: Thanks. This has code for both Volume plugins and the Plugins infra as well. I guess we can integrate with this.

**Comment by calavera** [comment]
Closing this because it has been ported to docker/docker as an independent PR in https://github.com/docker/docker/pull/13222

**Pull request closed without merging**
