### PR TITLE
Volume plugins w/ flag

### PR DESCRIPTION
**Pull request by progrium**
This is based on https://github.com/calavera/docker/pull/3 but with the `--volume-driver` flag. Pretty sure this is all that's needed.

### CODE REVIEW

**Comment by lukemarsden** [comment]
Thanks everyone for your work on this!

Two bits of feedback after doing some ad-hoc testing on this branch merged with #4...
- docker CLI behavior doesn't match with volumes blueprint when using a volume name (without forward slash):

```
$ sudo docker run -v foo:/test --volume-driver=flocker ubuntu bash
FATA[0000] Error response from daemon: cannot bind mount volume: foo volume paths must be absolute.
```

In the blueprint we agreed the following (implying the above syntax should be valid):

> All volumes need to have a name (as per requirement 3). The syntax for the -v flag of the docker run command will evolve to the following:
> `[{name,host_path}:]volume_path[:flags]`
> All but the volume_path are optional. The name and host_path fields are mutually exclusive. The name and host_path can be unambiguously distinguished by the fact that the host_path must be absolute (hence start with a /) while a leading / will be forbidden for the volume name. 
> [...]
> The name will be passed down to the extension as a way to consistently identify the volume.
- docker doesn't seem to fail when a volume driver is referenced which isn't loaded or loadable:

```
luke@slim:~$ sudo docker run -ti -v /foo:/test --volume-driver=flocker ubuntu bash                                         
root@b182c740064b:/# 
```

I don't have a `flocker` socket in `/usr/share/docker/plugins` at this point so I'm a bit suspicious that this didn't fail. Instead the regular "local" driver seems to have been used (there's an empty directory in the container, at least).

It would be great to see these issues addressed today so I can get to a full end-to-end test with flocker! ping @progrium @calavera @LK4D4 @crosbymichael @icecrime

**Comment by calavera** [comment]
good catch @lukemarsden. @progrium I can add those validations after merging this PR is you're not working on them.

**Comment by calavera** [comment]
merging this PR, I'm working on validations.

**Comment by lukemarsden** [comment]
Thanks @calavera!

FWIW, I think my first point goes deeper than validations.

If you look at `volume/plugins/adapter.go`, note that e.g.:

```
func (a *volumeAdapter) Mount() (string, error) {
    return a.proxy.Mount(a.name)
}
```

This should not be `a.name`, because that's just the name of the _driver_ (I think). The expected behaviour is that the _user-given name of the volume_ is handed to the plugin here. There doesn't seem to be any code in this branch for passing the user-given name of the volume (given `docker run -v name:volume_path` syntax where `name` does not start with a `/`) to the volume plugin.

**Comment by lukemarsden** [comment]
Oops, I might be wrong about my last point. `volumes/plugin/adapter.go` `Create()` takes a name, possibly the volume name. Checking...

**Comment by lukemarsden** [comment]
I've just traced this code back and found the following in `plugins/plugins.go`:

```
       for _, iface := range m.Implements {
               handler, handled := extpointHandlers[iface]
               if !handled {
                       continue
               }
               handler(p.Name, p.Client)
       }
```

I _think_ the `p.Name` here corresponds to `a.name` in the first code block I called. This means that e.g. the flocker plugin will get called with "flocker" as the volume name. If I'm right, this is wrong. It should be the volume name that the user typed when they typed `docker run -v name:volume_path`...

**Comment by progrium** [comment]
No. It's getting set from the name argument of Create:
https://github.com/calavera/docker/blob/plugin_discovery/volume/plugins/adapter.go#L19

**Comment by lukemarsden** [comment]
Ah yes, I see now. Sorry for the confusion. That definitely looks like it's coming in from the volume's name now. So I guess we just need to figure out how we can fix the validation for specifying a named volume along with a volume driver with `docker run -v name:volume_path --volume-driver=driver`.

**Comment by lukemarsden** [comment]
Is lazy activation of plugins supposed to work yet?

I tried this with a flocker plugin listening on `/usr/share/docker/plugins/flocker.sock`:

```
luke@slim:~$ sudo docker run -ti -v /foo:/test --volume-driver=flocker ubuntu bash                                         
root@0bbf0997e054:/# 
```

But didn't see any attempted HTTP connection on my flocker plugin (where I have HTTP request logging enabled).

I was expecting an HTTP request to: `/Plugin.Activate` on the socket.

**Comment by calavera** [comment]
I don't think bind mounts work with volumes extensions at all right now. I'm double checking

**Comment by lukemarsden** [comment]
OK, but _named_ volumes need to work with volume extensions :)

**Comment by lukemarsden** [comment]
(I guess I only accidentally used the bind-mount syntax because the named volume syntax wasn't working. Maybe I can try again without any `:` in my `-v`...)

**Comment by calavera** [comment]
named volumes goes through the same code path than bind mounts, so that's a problem.

**Comment by lukemarsden** [comment]
Re-running my latest test with an anonymous volume:

```
luke@slim:~$ sudo docker run -ti -v /test --volume-driver=flocker ubuntu bash
FATA[0000] Error response from daemon: Volumes Driver flocker isn't registered 
```

I'd expect the daemon to lazily attempt to connect to the flocker daemon in this case. The plugin wasn't available when docker was started (because it's a container) but I thought that the intention was to make the daemon look for a socket named "flocker.sock" if something later tries to use that volume driver... which exists:

```
luke@slim:~$ ls -alh /usr/share/docker/plugins/
total 8.0K
drwxr-xr-x 2 root root 4.0K May  8 19:18 .
drwxr-xr-x 3 root root 4.0K May  8 16:24 ..
srw-rw-rw- 1 root root    0 May  8 19:18 flocker.sock
```

**Comment by lukemarsden** [comment]
> named volumes goes through the same code path than bind mounts, so that's a problem.

Hmm, are named volumes supported at all in the current code? To be clear, by named volumes, I mean ones with a `-v name:volume_path` where `name` does not start with a `/`.

**Comment by lukemarsden** [comment]
One more bug report - I got my plugin running outside a container so that I could exercise the docker startup code, and I got this:

```
May 08 19:46:58 slim docker[14324]: time="2015-05-08T19:46:58.811029351+01:00" level=warning msg="Plugin load error:Post unix://Plugin.Activate: unsupported protocol scheme \"unix\""
```

Active socket here:

```
luke@slim:~$ ls -alh /usr/share/docker/plugins/                                                                            
total 8.0K
drwxr-xr-x 2 root root 4.0K May  8 19:42 .
drwxr-xr-x 3 root root 4.0K May  8 16:24 ..
srw-rw-rw- 1 root root    0 May  8 19:42 flocker.sock
```

**Comment by LK4D4** [comment]
@lukemarsden Thanks, for feedback. Could you pls provide script to up simple flocker plugin?

**Comment by lukemarsden** [comment]
@LK4D4 sure!

You can't run it as a container (because lazy activation doesn't work yet) but you could give this a try:

```
sudo mkdir -p /usr/share/docker/plugins
git clone https://github.com/clusterhq/powerstrip-flocker
cd powerstrip-flocker
git checkout testing_combined_volume_plugin
sudo twistd -noy powerstripflocker.tac
```

It won't actually work without a flocker deployment but it will log (to stdout) the HTTP requests it receives on the socket... which at the moment isn't any!

**Comment by LK4D4** [comment]
@lukemarsden Cool, thanks.

**Pull request merged**
